apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica-eks-deploy-1
  labels:
    name: practica-eks-deploy-1
    app: practica-eks-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: practica-eks-pod-1
      app: practica-eks-app
  template:
    metadata:
      name: practica-eks-pod-1
      labels:
        name: practica-eks-pod-1
        app: practica-eks-app
    spec:
      containers:
        - name: practica-eks-app1
          image: "882066515647.dkr.ecr.us-east-1.amazonaws.com/practica-eks-app1:latest"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
          livenessProbe:
            httpGet:
              path: /revisasivivo
              port: 3500
            initialDelaySeconds: 5
            periodSeconds: 5